sudo: required
services:
  - docker

  before_install:
  - docker build -t smontoyao/docker-react -f Dockerfile.dev .

script:
  #- docker run -e CI=true smontoyao/docker-react npm run test
  - docker run USERNAME/docker-react npm run test -- --coverage
